checkpointing_steps: null
dataset_path: ./dataset
gradient_accumulation_steps: 1
hub_model_id: null
hub_token: null
learning_rate: 5.0e-05
lr_scheduler_type: linear
max_length: 128
max_train_steps: 6237
model_name_or_path: BAAI/bge-large-en
num_train_epochs: 3
num_warmup_steps: 0
output_dir: ./sementic_search_outs
per_device_eval_batch_size: 8
per_device_train_batch_size: 24
report_to: all
resume_from_checkpoint: null
sanity_test: false
seed: null
use_peft: true
weight_decay: 0.0
with_tracking: true
